# Generated by Django 3.2.24 on 2024-12-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentTextTest',
            field=models.TextField(default='Um teste de conteudo'),
        ),
    ]
