# Generated by Django 3.2.24 on 2024-12-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_post_contenttexttest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contentTextTest',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Um teste de conteudo'),
        ),
    ]
